# SPDX-FileCopyrightText: 2022 Winni Neessen <winni@neessen.dev>
#
# SPDX-License-Identifier: CC0-1.0

name: SonarQube

permissions:
  contents: read

on:
  push:
    branches:
      - main # or the name of your main branch
  pull_request:
    branches:
      - main # or the name of your main branch
env:
  TEST_HOST: ${{ secrets.TEST_HOST }}
  TEST_FROM: ${{ secrets.TEST_USER }}
  TEST_ALLOW_SEND: "1"
  TEST_SMTPAUTH_USER: ${{ secrets.TEST_USER }}
  TEST_SMTPAUTH_PASS: ${{ secrets.TEST_PASS }}
  TEST_SMTPAUTH_TYPE: "LOGIN"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit

      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
        with:
          fetch-depth: 0
          
      - name: Setup Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version: '1.22.x'
          
      - name: Run unit Tests
        run: |
          go test -v -race --coverprofile=./cov.out ./...

      - uses: sonarsource/sonarqube-scan-action@540792c588b5c2740ad2bb4667db5cd46ae678f2 # master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          
      - uses: sonarsource/sonarqube-quality-gate-action@72f24ebf1f81eda168a979ce14b8203273b7c3ad # master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
